export const data = [
    { item:1,
      trend:"FEATURED",
      product_name:"Beardo Hair Growth Oil",
      MRPcut:"₹750",
      MRPcut1:750,
      MRP:"585",
      MRPsort:585,
      totaldiscount:165,
      discount:"22% Off",
      discountsort:22,
      total:"(400)",
      image_urls:"img/star4.png",
      rating:4,
      name:1,
      image_urlheart:"img/heart.png",
      image_url:"https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/b/e/beardo-hair-growth-oil.jpg",
    },
    
    {item:2,
    trend:"FEATURED",
    product_name:"Ustraa Hair Growth Vitalizer - Boost Hair Growth, Prevents Hairfall With Redensyl, Jojoba Oil",
    MRPcut:"₹699",
    MRPcut1:699,
    MRP:"559 ",
    MRPsort:559,
    totaldiscount:140,
    discount:"20% Off",
    discountsort:20,
    total:"(207)",
    image_urls:" img/star4.png",
    rating:4,
    name:20,
    image_urlheart:"img/heart.png",
    image_url:"https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/8/9/8904223818706hgv_1.jpg",
 },
    {item:3,
    trend:"FEATURED",
    product_name:"Bombay Shaving Company Beard Care Starter Gift Kit",
    MRPcut:"₹995",
    MRPcut1:995,
    MRP:"449",
    MRPsort:449,
    totaldiscount:546,
    discount:"55% Off",
    discountsort:55,
    total:"(500)",
    image_urls:" img/star5.png",
    rating:5,
    name:2,
    image_urlheart:"img/heart.png",
    image_url:"https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/3/3/3304c53655172771458_1pr.jpg",
 },
 {    item:4,
      trend:"FEATURED",
      product_name:"The Man Company Charcoal Face Wash With Ylang-Ylang & Argan",
      MRPcut:"₹349",
      MRPcut1:349,
      MRP:"276",
      MRPsort:276,
      totaldiscount:73,
      discount:"21% Off",
      discountsort:21,
      total:"(353)",
      image_urls:"img/star4.png",
      rating:4,
      name:18,
      image_urlheart:"img/heart.png",
      image_url:"https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/8/9/8907367001867_tmc_1.jpg",
    },
    
    {item:5,
    trend:"BESTSELLER",
    product_name:"MCaffeine Naked & Raw Tan Removal Coffee Body Scrub",
    MRPcut:"₹449",
    MRPcut1:449,
    MRP:"395 ",
    MRPsort:395,
    totaldiscount:54,
    discount:"12% Off",
    discountsort:12,
    total:"(36704)",
    image_urls:" img/star5.png",
    rating:5,
    name:12,
    image_urlheart:"img/heart.png",
    image_url:"https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/2/a/2abbbbanykmcf0000002_1.jpg",
 },
    {item:6,
    trend:"BESTSELLER",
    product_name:"MCaffeine Naked & Rich Deep Moisturizing Choco Body Butter",
    MRPcut:"₹645",
    MRPcut1:645,
    MRP:"575",
    MRPsort:575,
    totaldiscount:70,
    discount:"11% Off",
    discountsort:11,
    total:"(14593)",
    image_urls:" img/star4.png",
    rating:4,
    name:16,
    image_urlheart:"img/heart.png",
    image_url:"https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/c/d/cd9f379nykmcf0000008_1_new.jpg",
 },
 { item:7,
      trend:"BESTSELLER",
      product_name:"MCaffeine Naked & Raw Coffee Body Polishing Oil",
      MRPcut:"₹445",
      MRPcut1:445,
      MRP:"399",
      MRPsort:399,
      totaldiscount:46,
      discount:"10% Off",
      discountsort:10,
      total:"(8492)",
      image_urls:"img/star5.png", 
       rating:5,
       name:7,
      image_urlheart:"img/heart.png",
      image_url:"https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/c/4/c4c1578nymcfn0000031_1rvm.jpg",
    },
    
    {item:8,
    trend:"BESTSELLER",
    product_name:"MCaffeine Body Polishing Kit",
    MRPcut:"₹1094",
    MRPcut1:1094,
    MRP:"865 ",
    MRPsort:865,
    totaldiscount:229,
    discount:"21% Off",
    discountsort:21,
    total:"(3582)",
    image_urls:" img/star5.png",
    rating:5,
    name:4,
    image_urlheart:"img/heart.png",
    image_url:"https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/e/e/eecdff9nymcfcom00033_1new.jpg",
 },
    {item:9,
    trend:"BESTSELLER",
    product_name:"MCaffeine Naked & Raw Tan Removal Coffee Face Scrub",
    MRPcut:"₹349",
    MRPcut1:349,
    MRP:"315",
    MRPsort:315,
    totaldiscount:34,
    discount:"10% Off",
    discountsort:10,
    total:"(19744)",
    image_urls:" img/star4.png",
    rating:4,
    name:15,
    image_urlheart:"img/heart.png",
    image_url:"https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/a/c/acf7ff9nykmcf0000004_1new.jpg",
 },
 {    item:10,
      trend:"BESTSELLER",
      product_name:"MCaffeine Naked & Raw Deep Cleansing Coffee Face Wash",
      MRPcut:"₹349",
      MRPcut1:349,
      MRP:"315",
      MRPsort:315,
      totaldiscount:34,
      discount:"10% Off",
      discountsort:10,
      total:"(16938)",
      image_urls:"img/star4.png",
      rating:4,
      name:9,
      image_urlheart:"img/heart.png",
      image_url:"https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/7/8/78b6578nykmcf0000003_1rvm.jpg",
    },
    
    {item:11,
    trend:"BESTSELLER",
    product_name:"MCaffeine Naked & Raw Coffee Under Eye Cream - Relieves Dark Circles",
    MRPcut:"₹675",
    MRPcut1:675,
    MRP:"515 ",
    MRPsort:515,
    totaldiscount:160,
    discount:"10% Off",
    discountsort:10,
    total:"(5360)",
    image_urls:" img/star5.png",
    rating:5,
    name:8,
    image_urlheart:"img/heart.png",
    image_url:"https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/e/f/efd9578nymcfn0000029_1rvm.jpg",
 },
    {item:12,
    trend:"BESTSELLER",
    product_name:"MCaffeine Naked & Raw Moisturizing Coffee Body Lotion",
    MRPcut:"₹375",
    MRPcut1:375,
    MRP:"319",
    MRPsort:319,
    totaldiscount:56,
    discount:"15% Off",
    discountsort:15,
    total:"(5659)",
    image_urls:" img/star5.png",
    rating:5,
    name:11,
    image_urlheart:"img/heart.png",
    image_url:"https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/0/5/05e9578nymcfn0000025_1rvm.jpg",
 },
   { item:13,
    trend:"OFFER",
    product_name:"MCaffeine Naked Detox Hydrating Green Tea Face Serum",
    MRPcut:"₹625",
    MRPcut1:625,
    MRP:"555",
    MRPsort:535,
    totaldiscount:70,
    discount:"11% Off",
    discountsort:11,
    total:"(8702)",
    image_urls:" img/star4.png",
    rating:4,
    name:6,
    image_urlheart:"img/heart.png",
    image_url:"https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/3/c/3c45053NYMCFN0000022_1new.jpg",
 },
 { item:14,
      trend:"OFFER",
      product_name:"MCaffeine Naked & Raw Coffee Face Serum",
      MRPcut:"₹645",
      MRPcut1:645,
      MRP:"579",
      MRPsort:579,
      totaldiscount:66,
      discount:"10% Off",
      discountsort:10,
      total:"(5708)",
      image_urls:"img/star4.png",
      rating:4,
      name:10,
      image_urlheart:"img/heart.png",
      image_url:"https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/c/1/c157735nymcfn0000032_nkw1.jpg",
    },
    
    {item:15,
    trend:"OFFER",
    product_name:"MCaffeine Body Polishing Kit",
    MRPcut:"₹1269",
    MRPcut1:1269,
    MRP:"995 ",
    MRPsort:995,
    totaldiscount:274,
    discount:"22% Off",
    discountsort:22,
    total:"(655)",
    image_urls:" img/star5.png",
    rating:5,
    name:5,
    image_urlheart:"img/heart.png",
    image_url:"https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/c/2/c2b2509nymcfcom00057_1.jpg",
 },
    {item:16,
    trend:"",
    product_name:"Giorgio Armani Acqua Di Gio Eau De Toilette",
    MRPcut:"",
    
    MRP:"8250",
    MRPcut1:8250,
    MRPsort:8250,
    discount:"NOT APPLICABLE",
    discountsort:1000,
    totaldiscount:0,
    total:"(19744)",
    image_urls:" img/star4.png",
    rating:4,
    name:3,
    image_urlheart:"img/heart.png",
    image_url:"https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/g/i/giorgio-armani-acqua-di-gio-pour-homme-eau-de-toilette.jpg",
 },
 {    item:17,
      trend:"OFFER",
      product_name:"MCaffeine Naked & Raw Tan Removal Coffee Face Mask",
      MRPcut:"₹575",
      MRPcut1:575,
      MRP:"515",
      MRPsort:515,
      totaldiscount:60,
      discount:"10% Off",
      discountsort:10,
      total:"(293)",
      image_urls:"img/star5.png",
      rating:5,
      name:14,
      image_urlheart:"img/heart.png",
      image_url:"https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/b/8/b8e2578nykmcf0000009_1rvm.jpg",
    },
    
    {item:18,
    trend:"",
    product_name:"Paco Rabanne 1 Million Eau De Toilette",
    MRPcut:"",
    MRPcut1:4400,
    MRP:"4400 ",
    MRPsort:4400,
    discount:"NOT APPLICABLE",
    discountsort:1000,
    totaldiscount:0,
    total:"(5360)",
    image_urls:" img/star5.png",
    rating:5,
    name:17,
    image_urlheart:"img/heart.png",
    image_url:"https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/3/3/3349666007891_1.jpg",
 },
    {item:19,
    trend:"",
    product_name:"United Colors Of Benetton United Dreams Be Strong Eau De Toilette For Men",
    MRPcut:"₹1400",
    MRPcut1:1400,
    MRP:"700",
    MRPsort:700,
    totaldiscount:700,
    discount:"50% Off",
    discountsort:50,
    total:"(459)",
    image_urls:" img/star4.png",
    rating:4,
    name:19,
    image_urlheart:"img/heart.png",
    image_url:"https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/8/4/8433982002281_1_1.jpg",
 },
 {item:20,
    trend:"OFFER",
    product_name:"MCaffeine Exfoliate & Remove Tan Coffee Body Scrub - Pack Of 2",
    MRPcut:"₹898",
    MRPcut1:898,
    MRP:"719 ",
    MRPsort:719,
    totaldiscount:179,
    discount:"20% Off",
    discountsort:20,
    total:"(147)",
    image_urls:" img/star5.png",
    rating:5,
    name:13,
    image_urlheart:"img/heart.png",
    image_url:"https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/5/7/575fff9nymcfcom00045_1new.jpg",
 },
    
  ];